### ISSUE TITLE
failed to create io_uring ring fd Cannot allocate memory

### ISSUE THREAD

**Issue by lneves** [netty/netty-incubator-transport-io_uring#19]
Trying to use the io_uring based transport but getting errors on startup.
I think I have the necessary requirements (see below).

Exception in thread "main" java.lang.UnsatisfiedLinkError: failed to load the required native library
	at io.netty.incubator.channel.uring.IOUring.ensureAvailability(IOUring.java:63)
	at io.netty.incubator.channel.uring.IOUringEventLoop.<init>(IOUringEventLoop.java:64)
	at io.netty.incubator.channel.uring.IOUringEventLoopGroup.newChild(IOUringEventLoopGroup.java:117)
	at io.netty.incubator.channel.uring.IOUringEventLoopGroup.newChild(IOUringEventLoopGroup.java:31)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:68)
	at io.netty.incubator.channel.uring.IOUringEventLoopGroup.<init>(IOUringEventLoopGroup.java:100)
	at io.netty.incubator.channel.uring.IOUringEventLoopGroup.<init>(IOUringEventLoopGroup.java:93)
	at io.netty.incubator.channel.uring.IOUringEventLoopGroup.<init>(IOUringEventLoopGroup.java:86)
	at io.netty.incubator.channel.uring.IOUringEventLoopGroup.<init>(IOUringEventLoopGroup.java:75)
	at io.netty.incubator.channel.uring.IOUringEventLoopGroup.<init>(IOUringEventLoopGroup.java:58)
	at io.netty.incubator.channel.uring.IOUringEventLoopGroup.<init>(IOUringEventLoopGroup.java:44)
	at io.netty.incubator.channel.uring.IOUringEventLoopGroup.<init>(IOUringEventLoopGroup.java:37)
	at hello.TestServer.run(TestServer.java:39)
	at hello.TestServer.main(TestServer.java:89)
Caused by: java.lang.RuntimeException: failed to create io_uring ring fd Cannot allocate memory
	at io.netty.incubator.channel.uring.Native.ioUringSetup(Native Method)
	at io.netty.incubator.channel.uring.Native.createRingBuffer(Native.java:141)
	at io.netty.incubator.channel.uring.Native.createRingBuffer(Native.java:174)
	at io.netty.incubator.channel.uring.IOUring.<clinit>(IOUring.java:36)
	... 14 more

#########################################################

$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 33 (Thirty Three)
Release:	33
Codename:	ThirtyThree

$ uname -a
Linux TRU008012 5.9.9-200.fc33.x86_64 #1 SMP Thu Nov 19 21:25:45 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

pom.xml:

<dependency>
	<groupId>io.netty</groupId>
	<artifactId>netty-all</artifactId>
	<version>4.1.54.Final</version>
</dependency>

<dependency>
	<groupId>io.netty.incubator</groupId>
	<artifactId>netty-incubator-transport-native-io_uring</artifactId>
	<version>0.0.1.Final</version>
	<classifier>linux-x86_64</classifier>
</dependency>

**Comment by normanmaurer** [comment]
Thats most likely to the `memlock` settings on your system. Try to increase it for the user that runs the process.

For example see
https://access.redhat.com/solutions/61334
