### ISSUE TITLE
java.lang.RuntimeException: failed to create io_uring ring fd Cannot allocate memory

### ISSUE THREAD

**Issue by balamaci** [netty/netty-incubator-transport-io_uring#23]
Hi,
Sorry it probably is related to having to increase some kind of limits, but I don't know which or where this is mentioned, so I'm posting this in case someone encountered or has the same problem.

I'm getting a 
```java
Exception in thread "main" java.lang.UnsatisfiedLinkError: failed to load the required native library
	at io.netty.incubator.channel.uring.IOUring.ensureAvailability(IOUring.java:63)
	at io.netty.incubator.channel.uring.IOUringEventLoop.<init>(IOUringEventLoop.java:64)
	at io.netty.incubator.channel.uring.IOUringEventLoopGroup.newChild(IOUringEventLoopGroup.java:117)
	at io.netty.incubator.channel.uring.IOUringEventLoopGroup.newChild(IOUringEventLoopGroup.java:31)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:68)
	at io.netty.incubator.channel.uring.IOUringEventLoopGroup.<init>(IOUringEventLoopGroup.java:100)
	at io.netty.incubator.channel.uring.IOUringEventLoopGroup.<init>(IOUringEventLoopGroup.java:93)
	at io.netty.incubator.channel.uring.IOUringEventLoopGroup.<init>(IOUringEventLoopGroup.java:86)
	at io.netty.incubator.channel.uring.IOUringEventLoopGroup.<init>(IOUringEventLoopGroup.java:75)
	at io.netty.incubator.channel.uring.IOUringEventLoopGroup.<init>(IOUringEventLoopGroup.java:58)
	at io.netty.incubator.channel.uring.IOUringEventLoopGroup.<init>(IOUringEventLoopGroup.java:44)
	at com.balamaci.net.async.netty.NettyServerStart.main(NettyServerStart.java:20)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:128)
Caused by: java.lang.RuntimeException: failed to create io_uring ring fd Cannot allocate memory
	at io.netty.incubator.channel.uring.Native.ioUringSetup(Native Method)
	at io.netty.incubator.channel.uring.Native.createRingBuffer(Native.java:141)
	at io.netty.incubator.channel.uring.Native.createRingBuffer(Native.java:174)
	at io.netty.incubator.channel.uring.IOUring.<clinit>(IOUring.java:36)
	... 17 more

Process finished with exit code 1
```
Initially on 5.4 Kernel in Ubuntu, upgraded to 5.9.10 but still same.

Code is https://github.com/balamaci/async-profiler-playground/blob/master/src/main/java/com/balamaci/net/async/netty/NettyServerStart.java

Running on JDK 15.

**Comment by 1Jo1** [comment]
that's odd, are you out of memory?

**Comment by balamaci** [comment]
Not unless I need more than 6GB of memory.
I've debuged the Java part and it gets to the native of
```java
        long[][] values = ioUringSetup(ringSize);
``` 
with ringsize = 4096

Also I've tried to trace all system calls made, it seems to reach **sys_enter_io_uring_setup**.

Syscall Requested: tracepoint:syscalls:sys_enter_io_uring_setup
Process Name: java
Syscall Requested: tracepoint:syscalls:sys_enter_openat
Process Name: java
Syscall Requested: tracepoint:syscalls:sys_enter_newfstat
Process Name: java
Syscall Requested: tracepoint:syscalls:sys_enter_read
Process Name: java
Syscall Requested: tracepoint:syscalls:sys_enter_read
Process Name: java
Syscall Requested: tracepoint:syscalls:sys_enter_close
Process Name: java
Syscall Requested: tracepoint:syscalls:sys_enter_openat
Process Name: java
Syscall Requested: tracepoint:syscalls:sys_enter_openat
Process Name: java
Syscall Requested: tracepoint:syscalls:sys_enter_openat
Process Name: java
Syscall Requested: tracepoint:syscalls:sys_enter_openat
Process Name: java
Syscall Requested: tracepoint:syscalls:sys_enter_openat
Process Name: java
Syscall Requested: tracepoint:syscalls:sys_enter_openat
Process Name: java
Syscall Requested: tracepoint:syscalls:sys_enter_openat
Process Name: java
Syscall Requested: tracepoint:syscalls:sys_enter_openat
Process Name: java
Syscall Requested: tracepoint:syscalls:sys_enter_openat
Process Name: java
Syscall Requested: tracepoint:syscalls:sys_enter_openat
Process Name: java
Syscall Requested: tracepoint:syscalls:sys_enter_openat
Process Name: java
Syscall Requested: tracepoint:syscalls:sys_enter_openat
Process Name: java
Syscall Requested: tracepoint:syscalls:sys_enter_write
Process Name: java
Syscall Requested: tracepoint:syscalls:sys_enter_pread64



list continues but I can't be sure where it fails, for sure there aren't any other 'uring' showing up.

**Comment by normanmaurer** [comment]
I suspect it is the memlock setting. See https://github.com/netty/netty-incubator-transport-io_uring/issues/19

**Comment by 1Jo1** [comment]
probably memlock, please run `ulimit -a`

**Comment by balamaci** [comment]
Hi, thank you very much, there was a 64 limit, after increase, worked without problems.

**Comment by normanmaurer** [comment]
Ok cool ... let me add something to the readme

**Comment by normanmaurer** [comment]
https://github.com/netty/netty-incubator-transport-io_uring/pull/25
