### ISSUE TITLE
Release 0.0.26.Final

### ISSUE THREAD

**Issue by andreasdc** [netty/netty-incubator-transport-io_uring#261]
Hey, I think 0.0.26.Final version should be released, as it contains pretty important patches like: https://github.com/netty/netty-incubator-transport-io_uring/pull/244

**Comment by normanmaurer** [comment]
Sure we can do this .

**Comment by normanmaurer** [comment]
done

**Comment by andreasdc** [comment]
> done

Nice, good job 🚀 Do you think it's possible to improve the performance even further?

**Comment by normanmaurer** [comment]
@andreasdc yes for sure... That said once netty-4.2.0.Final was released we will stop working on this repository and archive it as io_uring was merged into netty-4.2.0.Final

**Comment by andreasdc** [comment]
> @andreasdc yes for sure... That said once netty-4.2.0.Final was released we will stop working on this repository and archive it as io_uring was merged into netty-4.2.0.Final

That's cool, when do you think netty 4.2.0 will be released?

**Comment by normanmaurer** [comment]
soonish... The next 1-2 months

**Comment by normanmaurer** [comment]
Btw feel free to test `netty-4.2.0.rc1`

**Comment by andreasdc** [comment]
> Btw feel free to test `netty-4.2.0.rc1`

Is it mainly stable or bugs can happen?

**Comment by normanmaurer** [comment]
@andreasdc it's software so there can always be bugs... It's a release candidate so we consider it almost ready

**Comment by andreasdc** [comment]
> @andreasdc it's software so there can always be bugs... It's a release candidate so we consider it almost ready

Were there any big changes or optimizations in this version?

**Comment by normanmaurer** [comment]
@andreasdc the io_uring transport was mostly rewritten... Please test it if you are interested.

**Comment by andreasdc** [comment]
> @andreasdc the io_uring transport was mostly rewritten... Please test it if you are interested.

Did I understand it well?
MultiThreadIoEventLoopGroup should be used instead of IOUringEventLoopGroup along with IoUringIoHandler.newFactory()?
Is it better than previous implementation?

**Comment by chrisvest** [comment]
> MultiThreadIoEventLoopGroup should be used instead of IOUringEventLoopGroup along with IoUringIoHandler.newFactory()?

Yes, that is correct.

> Is it better than previous implementation?

We think so, but we're not running your application in your environment, so giving the release candidate a try is a good way to help build confidence.

Your profile shows all the time is spent in the `ioUringEnter` system call. So that's either processing IO commands, or simply waiting for stuff to happen, i.e. idling.

**Comment by andreasdc** [comment]
Actually I have this error, I have it in my logs around 150 times, out of couple thousand connections.
```[multiThreadIoEventLoopGroup-3-26/WARN] [io.netty.channel.uring.CompletionQueue]: Unexpected exception in the IO event loop.
java.lang.NullPointerException: Cannot invoke "io.netty.channel.ChannelOutboundBuffer.current()" because "channelOutboundBuffer" is null
	at io.netty.channel.uring.AbstractIoUringStreamChannel$IoUringStreamUnsafe.writeComplete0(AbstractIoUringStreamChannel.java:409) ~[bungeecord-fork.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:x:unknown]
	at io.netty.channel.uring.AbstractIoUringChannel$AbstractUringUnsafe.writeComplete(AbstractIoUringChannel.java:796) ~[bungeecord-fork.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:x:unknown]
	at io.netty.channel.uring.AbstractIoUringChannel$AbstractUringUnsafe.handle(AbstractIoUringChannel.java:419) ~[bungeecord-fork.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:x:unknown]
	at io.netty.channel.uring.IoUringIoHandler$DefaultIoUringIoRegistration.handle(IoUringIoHandler.java:370) ~[bungeecord-fork.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:x:unknown]
	at io.netty.channel.uring.IoUringIoHandler.handle(IoUringIoHandler.java:117) ~[bungeecord-fork.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:x:unknown]
	at io.netty.channel.uring.UserData.decode(UserData.java:38) ~[bungeecord-fork.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:x:unknown]
	at io.netty.channel.uring.CompletionQueue.process(CompletionQueue.java:113) ~[bungeecord-fork.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:x:unknown]
	at io.netty.channel.uring.IoUringIoHandler.run(IoUringIoHandler.java:97) ~[bungeecord-fork.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:x:unknown]
	at io.netty.channel.SingleThreadIoEventLoop.runIo(SingleThreadIoEventLoop.java:184) ~[bungeecord-fork.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:x:unknown]
	at io.netty.channel.SingleThreadIoEventLoop.run(SingleThreadIoEventLoop.java:156) ~[bungeecord-fork.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:x:unknown]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:1123) ~[bungeecord-fork.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:x:unknown]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[bungeecord-fork.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:x:unknown]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[bungeecord-fork.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:x:unknown]
	at java.lang.Thread.run(Thread.java:1575) [?:?]```
