### ISSUE TITLE
LinuxSocket NoClassDefFoundError

### ISSUE THREAD

**Issue by 1Jo1** [netty/netty-incubator-transport-io_uring#47]
when I run a netty example https://github.com/1Jo1/netty-io_uring-kernel-debugging/blob/master/src/main/java/uring/netty/example/EchoUringServer.java

```
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class io.netty.incubator.channel.uring.LinuxSocket
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
	at java.lang.Runtime.load0(Runtime.java:810)
	at java.lang.System.load(System.java:1088)
	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36)
	at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:351)
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:205)
	at io.netty.incubator.channel.uring.Native.loadNativeLibrary(Native.java:219)
	at io.netty.incubator.channel.uring.Native.<clinit>(Native.java:55)
	at io.netty.incubator.channel.uring.IOUringEventLoopGroup.<init>(IOUringEventLoopGroup.java:58)
	at io.netty.incubator.channel.uring.IOUringEventLoopGroup.<init>(IOUringEventLoopGroup.java:44)
	at uring.netty.example.UringBenchmark.main(UringBenchmark.java:49)
```

as far as I know this #31 PR  has caused this bug, it could be related to the maven build change

netty-io_uring version: current master aa26d0a6893d619d52a50a77d7d05b89d6c42859

**Comment by 1Jo1** [comment]
@normanmaurer its probably maven build issue as LinuxSocket was not changed, what do you think?

**Comment by normanmaurer** [comment]
@1Jo1 fixed by https://github.com/netty/netty-incubator-transport-io_uring/pull/48
