### ISSUE TITLE
Errro on ubuntu 20.04 kenerl 5.10

### ISSUE THREAD

**Issue by azzahrah** [netty/netty-incubator-transport-io_uring#9]
Exception in thread "Thread-0" java.lang.UnsatisfiedLinkError: could not load a native library: netty_transport_native_io_uring_x86_64
        at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:226)
        at io.netty.incubator.channel.uring.Native.loadNativeLibrary(Native.java:219)
        at io.netty.incubator.channel.uring.Native.<clinit>(Native.java:55)
        at io.netty.incubator.channel.uring.IOUringEventLoopGroup.<init>(IOUringEventLoopGroup.java:58)
        at io.netty.incubator.channel.uring.IOUringEventLoopGroup.<init>(IOUringEventLoopGroup.java:44)
        at io.netty.incubator.channel.uring.IOUringEventLoopGroup.<init>(IOUringEventLoopGroup.java:37)
        at com.pusatgps.bootstraps.Gt06Bootstrap.init(Gt06Bootstrap.java:81)
        at com.pusatgps.main.ServerController.init(ServerController.java:115)
        at com.pusatgps.main.Context.init(Context.java:349)
        at com.pusatgps.threads.ThreadStartServer.run(ThreadStartServer.java:26)
        Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_transport_native_io_uring
                at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:226)
                at io.netty.incubator.channel.uring.Native.loadNativeLibrary(Native.java:222)
                ... 8 more
        Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_transport_native_io_uring.so
                at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:175)
                ... 9 more
                Suppressed: java.lang.UnsatisfiedLinkError: no netty_transport_native_io_uring in java.library.path: [/usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-g                                             nu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
                        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
                        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
                        at java.base/java.lang.System.loadLibrary(System.java:1873)
                        at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
                        at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:351)
                        at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
                        ... 9 more
                        Suppressed: java.lang.UnsatisfiedLinkError: no netty_transport_native_io_uring in java.library.path: [/usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64                                             -linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
                                at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
                                at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
                                at java.base/java.lang.System.loadLibrary(System.java:1873)
                                at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
                                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                                at java.base/java.lang.reflect.Method.invoke(Method.java:566)
                                at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:385)
                                at java.base/java.security.AccessController.doPrivileged(Native Method)
                                at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:377)
                                at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:341)
                                ... 10 more
Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_transport_native_io_uring_x86_64.so
        at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:175)
        ... 9 more
        Suppressed: java.lang.UnsatisfiedLinkError: no netty_transport_native_io_uring_x86_64 in java.library.path: [/usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-gn                                             u, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
                at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
                at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
                at java.base/java.lang.System.loadLibrary(System.java:1873)
                at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
                at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:351)
                at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
                ... 9 more
                Suppressed: java.lang.UnsatisfiedLinkError: no netty_transport_native_io_uring_x86_64 in java.library.path: [/usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-                                             linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
                        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
                        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
                        at java.base/java.lang.System.loadLibrary(System.java:1873)
                        at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
                        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
                        at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:385)
                        at java.base/java.security.AccessController.doPrivileged(Native Method)
                        at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:377)
                        at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:341)
                        ... 10 more

**Comment by normanmaurer** [comment]
@azzahrah I just tested it and it works... can you show me your dependency configuration ?

**Comment by azzahrah** [comment]
@normanmaurer  problem solve just update dependencies 

<dependency>
    <groupId>io.netty.incubator</groupId>
    <artifactId>netty-incubator-transport-native-io_uring</artifactId>
    <version>0.0.1.Final</version>
    <classifier>linux-x86_64</classifier>
</dependency>
